version: '3'
services:
  hand:
    build:
      context: .
      dockerfile: hand.dockerfile
    container_name: hand-container-ros2
    tty: true
    volumes:
      - /home/piotr/ros_ws/Inspire-Robots-Hand-Teleoperation/ros2_ws:/ros_ws
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"